#include "../../src/cxbx/src/win32/CxbxKrnl/EmuVshDecoder.h"

#include <cstdio>
#include <cstring>
#include <exception>
#include <string>

namespace
{
int g_failures = 0;

void Check(bool condition, const char* name)
{
    if(!condition)
    {
        std::fprintf(stderr, "FAIL %s\n", name);
        ++g_failures;
    }
}

constexpr DWORD kXboxProgram[] = {
    0x00052078u,
    0x00000000u,
    0x00E0001Bu,
    0x0836186Cu,
    0x00008800u,
    0x00000000u,
    0x00E0201Bu,
    0x0836186Cu,
    0x00004800u,
    0x00000000u,
    0x00E0401Bu,
    0x0836186Cu,
    0x00002800u,
    0x00000000u,
    0x00E0601Bu,
    0x0836186Cu,
    0x00001800u,
    0x00000000u,
    0x0020061Bu,
    0x0836006Cu,
    0x0000F819u,
};

constexpr DWORD kXboxDeclaration[] = {
    0x10000000u,
    0x40020000u,
    0xFFFFFFFFu,
};
} // namespace

int RunTests()
{
    DWORD* translated = XTL::EmuVshRecompileXboxFunction(kXboxProgram);
    Check(translated != nullptr, "recompiler returns bytecode");
    if(translated == nullptr)
    {
        return g_failures;
    }

    const std::uint32_t hash = XTL::VshDiagnostics::HashXboxFunction(kXboxProgram);
    Check(hash == 0x79E4E0BEu, "stable Xbox-function hash");

    const XTL::VshDiagnostics::ValidationResult validation =
        XTL::VshDiagnostics::ValidateD3D8Translation(kXboxProgram, translated);
    Check(validation.valid, "generated bytecode validates");
    Check(validation.message == "ok", "validator success reason");

    const std::vector<std::string> xboxListing = XTL::VshDiagnostics::DecodeXboxFunction(kXboxProgram);
    const std::vector<std::string> d3dListing =
        XTL::VshDiagnostics::DecodeD3D8Function(translated, 4 + 5 * 20);
    Check(xboxListing.size() == 5, "decoded NV2A instruction count");
    Check(d3dListing.size() == 7, "decoded D3D8 instruction count");
    Check(xboxListing.front().find("mac=dp4") != std::string::npos, "NV2A listing names DP4");
    Check(d3dListing.front().find("op=mov") != std::string::npos, "D3D8 listing names seed MOV");
    Check(d3dListing.back().find("dst=oR0.xyzw") != std::string::npos, "D3D8 listing identifies oPos");

    const DWORD unknownOpcode[] = { 0xFFFE0101u, 0x00001234u, 0x0000FFFFu };
    const XTL::VshDiagnostics::ValidationResult unknownValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(unknownOpcode, 3);
    Check(!unknownValidation.valid, "unknown opcode rejected");
    Check(unknownValidation.instructionIndex == 0, "unknown opcode location");

    const DWORD truncatedInstruction[] = { 0xFFFE0101u, 0x00000001u, 0x800F0000u };
    const XTL::VshDiagnostics::ValidationResult truncatedValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(truncatedInstruction, 3);
    Check(!truncatedValidation.valid, "truncated instruction rejected");
    Check(truncatedValidation.message == "instruction is truncated", "truncated instruction reason");

    const DWORD invalidConstant[] = {
        0xFFFE0101u,
        0x00000001u,
        0xC00F0000u,
        0xA0E40060u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::ValidationResult constantValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(invalidConstant, 5);
    Check(!constantValidation.valid, "constant above c95 rejected");
    Check(constantValidation.message.find("exceeds c95") != std::string::npos,
          "invalid constant reason");

    const DWORD missingPosition[] = {
        0xFFFE0101u,
        0x00000001u,
        0x800F0000u,
        0x90E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::ValidationResult positionValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(missingPosition, 5);
    Check(!positionValidation.valid, "missing oPos rejected");
    Check(positionValidation.message == "shader never writes oPos", "missing oPos reason");

    std::vector<DWORD> oversizedShader = {
        0xFFFE0101u,
        0x00000001u,
        0xC00F0000u,
        0x90E40000u,
    };
    oversizedShader.insert(oversizedShader.end(), 128, 0x00000000u);
    oversizedShader.push_back(0x0000FFFFu);
    const XTL::VshDiagnostics::ValidationResult oversizedValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(oversizedShader.data(), oversizedShader.size());
    Check(!oversizedValidation.valid, "shader above 128 instructions rejected");
    Check(oversizedValidation.instructionIndex == 128, "instruction-limit location");
    Check(oversizedValidation.message.find("limit of 128") != std::string::npos,
          "instruction-limit reason");

    DWORD translatedDeclaration[8] = {};
    const int declarationTokens =
        XTL::EmuVshTranslateXboxDeclaration(kXboxDeclaration, translatedDeclaration, 8);
    Check(declarationTokens == 3, "declaration token count");
    Check(translatedDeclaration[1] == 0x40020000u, "PC declaration token remains stable");

    std::FILE* capture = nullptr;
#if defined(_WIN32)
    const errno_t captureError = ::tmpfile_s(&capture);
    Check(captureError == 0, "diagnostic capture file result");
#else
    capture = std::tmpfile();
#endif
    Check(capture != nullptr, "diagnostic capture file");
    if(capture != nullptr)
    {
        const XTL::VshDiagnostics::TranslationCapture translationCapture = {
            kXboxProgram,
            translated,
            kXboxDeclaration,
            translatedDeclaration,
        };
        XTL::VshDiagnostics::DumpRejectedTranslation(capture, translationCapture);
        const int seekResult = std::fseek(capture, 0, SEEK_SET);
        Check(seekResult == 0, "diagnostic capture seek");
        if(seekResult == 0)
        {
            char output[256] = {};
            const std::size_t bytesRead = std::fread(output, 1, sizeof(output) - 1, capture);
            Check(std::ferror(capture) == 0, "diagnostic capture read");
            output[bytesRead] = '\0';
            Check(std::strstr(output, "VSH| rejected hash=") != nullptr, "rejection capture header");
        }
        std::fclose(capture);
    }

    delete[] translated;
    if(g_failures == 0)
    {
        std::puts("PASS host vertex-shader recompiler");
    }
    else
    {
        std::printf("INFO hash=0x%08X\n", hash);
    }
    return g_failures;
}

int main()
{
    try
    {
        return RunTests();
    }
    catch(const std::exception& exception)
    {
        std::fprintf(stderr, "FAIL unexpected exception: %s\n", exception.what());
        return 1;
    }
    catch(...)
    {
        std::fputs("FAIL unexpected non-standard exception\n", stderr);
        return 1;
    }
}
