#include "../../src/cxbx/src/win32/CxbxKrnl/EmuVshDecoder.h"

#include <array>
#include <cstdio>
#include <cstring>
#include <exception>
#include <iterator>
#include <string>

namespace
{
int g_failures = 0;

void Check(bool condition, const char* name)
{
    if(!condition)
    {
        std::fprintf(stderr, "FAIL %s\n", name);
        ++g_failures;
    }
}

constexpr DWORD kXboxProgram[] = {
    0x00052078u,
    0x00000000u,
    0x00E0001Bu,
    0x0836186Cu,
    0x00008800u,
    0x00000000u,
    0x00E0201Bu,
    0x0836186Cu,
    0x00004800u,
    0x00000000u,
    0x00E0401Bu,
    0x0836186Cu,
    0x00002800u,
    0x00000000u,
    0x00E0601Bu,
    0x0836186Cu,
    0x00001800u,
    0x00000000u,
    0x0020061Bu,
    0x0836006Cu,
    0x0000F819u,
};

constexpr DWORD kXboxDeclaration[] = {
    0x10000000u,
    0x40020000u,
    0xFFFFFFFFu,
};
} // namespace

int RunTests()
{
    DWORD* translated = XTL::EmuVshRecompileXboxFunction(kXboxProgram);
    Check(translated != nullptr, "recompiler returns bytecode");
    if(translated == nullptr)
    {
        return g_failures;
    }

    const std::uint32_t hash = XTL::VshDiagnostics::HashXboxFunction(kXboxProgram);
    Check(hash == 0x79E4E0BEu, "stable Xbox-function hash");

    const XTL::VshDiagnostics::ValidationResult validation =
        XTL::VshDiagnostics::ValidateD3D8Translation(kXboxProgram, translated);
    Check(validation.valid, "generated bytecode validates");
    Check(validation.message == "ok", "validator success reason");

    const std::vector<std::string> xboxListing = XTL::VshDiagnostics::DecodeXboxFunction(kXboxProgram);
    const std::vector<std::string> d3dListing =
        XTL::VshDiagnostics::DecodeD3D8Function(translated, 4 + 5 * 20);
    Check(xboxListing.size() == 5, "decoded NV2A instruction count");
    Check(d3dListing.size() == 6, "decoded optimized D3D8 instruction count");
    Check(xboxListing.front().find("mac=dp4") != std::string::npos, "NV2A listing names DP4");
    Check(d3dListing.front().find("op=dp4") != std::string::npos, "dead position seed removed");
    Check(d3dListing.back().find("dst=oR0.xyzw") != std::string::npos, "D3D8 listing identifies oPos");

    const DWORD unknownOpcode[] = { 0xFFFE0101u, 0x00001234u, 0x0000FFFFu };
    const XTL::VshDiagnostics::ValidationResult unknownValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(unknownOpcode, 3);
    Check(!unknownValidation.valid, "unknown opcode rejected");
    Check(unknownValidation.instructionIndex == 0, "unknown opcode location");
    DWORD unknownOptimizationInput[] = { 0xFFFE0101u, 0x00001234u, 0x0000FFFFu };
    const XTL::VshDiagnostics::OptimizationResult unknownOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(unknownOptimizationInput, std::size(unknownOptimizationInput));
    Check(!unknownOptimization.valid, "unknown opcode is not optimized");
    Check(unknownOptimizationInput[1] == 0x00001234u, "failed optimization leaves bytecode unchanged");

    const DWORD truncatedInstruction[] = { 0xFFFE0101u, 0x00000001u, 0x800F0000u };
    const XTL::VshDiagnostics::ValidationResult truncatedValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(truncatedInstruction, 3);
    Check(!truncatedValidation.valid, "truncated instruction rejected");
    Check(truncatedValidation.message == "instruction is truncated", "truncated instruction reason");

    const DWORD invalidConstant[] = {
        0xFFFE0101u,
        0x00000001u,
        0xC00F0000u,
        0xA0E40060u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::ValidationResult constantValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(invalidConstant, 5);
    Check(!constantValidation.valid, "constant above c95 rejected");
    Check(constantValidation.message.find("exceeds c95") != std::string::npos,
          "invalid constant reason");

    const DWORD missingPosition[] = {
        0xFFFE0101u,
        0x00000001u,
        0x800F0000u,
        0x90E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::ValidationResult positionValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(missingPosition, 5);
    Check(!positionValidation.valid, "missing oPos rejected");
    Check(positionValidation.message == "shader never writes oPos", "missing oPos reason");

    DWORD overwrittenTemporary[] = {
        0xFFFE0101u,
        0x00000001u,
        0x800F0000u,
        0x90E40000u,
        0x00000001u,
        0x800F0000u,
        0x90E40001u,
        0x00000001u,
        0xC00F0000u,
        0x80E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::OptimizationResult overwriteOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(overwrittenTemporary, std::size(overwrittenTemporary));
    Check(overwriteOptimization.valid, "dead-write optimization succeeds");
    Check(overwriteOptimization.beforeInstructionCount == 3, "dead-write input count");
    Check(overwriteOptimization.afterInstructionCount == 2, "overwritten temporary removed");
    Check((overwrittenTemporary[3] & 0x7FFu) == 1, "remaining temporary uses latest input");

    DWORD partialTemporary[] = {
        0xFFFE0101u,
        0x00000001u,
        0x80030000u,
        0x90E40000u,
        0x00000001u,
        0xC0010000u,
        0x80E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::OptimizationResult partialOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(partialTemporary, std::size(partialTemporary));
    Check(partialOptimization.valid, "partial-mask optimization succeeds");
    Check(((partialTemporary[2] >> 16) & 0xFu) == 0x1u, "dead destination component removed");

    DWORD dotProductDependency[] = {
        0xFFFE0101u,
        0x00000001u,
        0x80020000u,
        0x90550000u,
        0x00000008u,
        0xC0010000u,
        0x80E40000u,
        0x80E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::OptimizationResult dotOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(dotProductDependency, std::size(dotProductDependency));
    Check(dotOptimization.afterInstructionCount == 2, "dot product preserves all source lanes");
    Check(((dotProductDependency[2] >> 16) & 0xFu) == 0x2u, "dot product preserves Y dependency");

    DWORD relativeAddress[] = {
        0xFFFE0101u,
        0x00000001u,
        0xB0010000u,
        0x90E40000u,
        0x00000001u,
        0x800F0000u,
        0xA0E42000u,
        0x00000001u,
        0xC00F0000u,
        0x80E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::OptimizationResult relativeOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(relativeAddress, std::size(relativeAddress));
    Check(relativeOptimization.valid, "relative-address optimization succeeds");
    Check(relativeOptimization.afterInstructionCount == 3, "relative addressing preserves a0 write");

    DWORD unusedAddress[] = {
        0xFFFE0101u,
        0x00000001u,
        0xB0010000u,
        0x90E40000u,
        0x00000001u,
        0x800F0000u,
        0xA0E40000u,
        0x00000001u,
        0xC00F0000u,
        0x80E40000u,
        0x0000FFFFu,
    };
    const XTL::VshDiagnostics::OptimizationResult addressOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(unusedAddress, std::size(unusedAddress));
    Check(addressOptimization.valid, "unused-address optimization succeeds");
    Check(addressOptimization.afterInstructionCount == 2, "unused a0 write removed");

    std::vector<DWORD> oversizedShader = {
        0xFFFE0101u,
        0x00000001u,
        0xC00F0000u,
        0x90E40000u,
    };
    oversizedShader.insert(oversizedShader.end(), 128, 0x00000000u);
    oversizedShader.push_back(0x0000FFFFu);
    const XTL::VshDiagnostics::ValidationResult oversizedValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(oversizedShader.data(), oversizedShader.size());
    Check(!oversizedValidation.valid, "shader above 128 instructions rejected");
    Check(oversizedValidation.instructionIndex == 128, "instruction-limit location");
    Check(oversizedValidation.message.find("limit of 128") != std::string::npos,
          "instruction-limit reason");
    const XTL::VshDiagnostics::OptimizationResult oversizedOptimization =
        XTL::VshDiagnostics::OptimizeD3D8Function(oversizedShader.data(), oversizedShader.size());
    Check(oversizedOptimization.beforeInstructionCount == 129, "oversized optimizer input count");
    Check(oversizedOptimization.afterInstructionCount == 1, "dead NOP instructions removed");
    const XTL::VshDiagnostics::ValidationResult optimizedOversizedValidation =
        XTL::VshDiagnostics::ValidateD3D8Function(oversizedShader.data(), oversizedOptimization.tokenCount);
    Check(optimizedOversizedValidation.valid, "optimized shader meets instruction limit");

    const DWORD cpuDeclaration[] = {
        0x20000000u,
        0x40320000u,
        0x40400001u,
        0x40250002u,
        0xFFFFFFFFu,
    };
    std::array<std::uint8_t, 20> cpuVertex{};
    const float cpuPosition[] = { 2.0f, 3.0f, 4.0f };
    const DWORD cpuColor = 0x80402010u;
    const std::int16_t cpuShorts[] = { -2, 7 };
    std::memcpy(cpuVertex.data(), cpuPosition, sizeof(cpuPosition));
    std::memcpy(cpuVertex.data() + sizeof(cpuPosition), &cpuColor, sizeof(cpuColor));
    std::memcpy(cpuVertex.data() + sizeof(cpuPosition) + sizeof(cpuColor), cpuShorts, sizeof(cpuShorts));
    const XTL::VshDiagnostics::VertexStreamView cpuStream = {
        cpuVertex.data(),
        cpuVertex.size(),
        cpuVertex.size(),
    };
    std::array<float, 16 * 4> cpuInputs{};
    Check(XTL::VshDiagnostics::DecodeXboxVertex(cpuDeclaration, &cpuStream, 1, 0,
                                                cpuInputs.data(), cpuInputs.size()),
          "CPU fallback vertex declaration decodes");
    Check(cpuInputs[0] == 2.0f && cpuInputs[1] == 3.0f && cpuInputs[2] == 4.0f && cpuInputs[3] == 1.0f,
          "FLOAT3 expands with W=1");
    Check(cpuInputs[4] == 64.0f / 255.0f && cpuInputs[5] == 32.0f / 255.0f &&
              cpuInputs[6] == 16.0f / 255.0f && cpuInputs[7] == 128.0f / 255.0f,
          "D3DCOLOR expands to RGBA");
    Check(cpuInputs[8] == -2.0f && cpuInputs[9] == 7.0f && cpuInputs[10] == 0.0f && cpuInputs[11] == 1.0f,
          "SHORT2 expands with Z=0 W=1");

    const DWORD packedDeclaration[] = {
        0x20000000u,
        0x40350000u,
        0x40160001u,
        0x40340002u,
        0xFFFFFFFFu,
    };
    std::array<std::uint8_t, 13> packedVertex{};
    const std::int16_t short3[] = { -3, 4, 9 };
    const DWORD normalizedPacked = 0x1FFu | (0x600u << 11);
    const std::uint8_t packedBytes[] = { 1, 2, 255 };
    std::memcpy(packedVertex.data(), short3, sizeof(short3));
    std::memcpy(packedVertex.data() + sizeof(short3), &normalizedPacked, sizeof(normalizedPacked));
    std::memcpy(packedVertex.data() + sizeof(short3) + sizeof(normalizedPacked), packedBytes, sizeof(packedBytes));
    const XTL::VshDiagnostics::VertexStreamView packedStream = {
        packedVertex.data(),
        packedVertex.size(),
        packedVertex.size(),
    };
    Check(XTL::VshDiagnostics::DecodeXboxVertex(packedDeclaration, &packedStream, 1, 0,
                                                cpuInputs.data(), cpuInputs.size()),
          "extended Xbox declaration types decode");
    Check(cpuInputs[0] == -3.0f && cpuInputs[1] == 4.0f && cpuInputs[2] == 9.0f && cpuInputs[3] == 1.0f,
          "SHORT3 expands with W=1");
    Check(cpuInputs[4] > 0.49f && cpuInputs[5] < -0.49f && cpuInputs[6] == 0.0f,
          "NORMPACKED3 sign-extends and normalizes");
    Check(cpuInputs[8] == 1.0f && cpuInputs[9] == 2.0f && cpuInputs[10] == 255.0f,
          "PBYTE3 expands to scalar components");

    std::array<float, 192 * 4> cpuConstants{};
    cpuConstants[0] = 1.0f;
    cpuConstants[5] = 1.0f;
    cpuConstants[10] = 1.0f;
    cpuConstants[15] = 1.0f;
    cpuInputs.fill(0.0f);
    cpuInputs[0] = 2.0f;
    cpuInputs[1] = 3.0f;
    cpuInputs[2] = 4.0f;
    cpuInputs[3] = 1.0f;
    std::array<float, 4> cpuOutputPosition{};
    std::array<float, 4> cpuOutputColor{};
    std::array<float, 4 * 4> cpuOutputTexCoord{};
    cpuOutputTexCoord.fill(99.0f);
    Check(XTL::VshDiagnostics::ExecuteXboxVertexShader(kXboxProgram, cpuConstants.data(), cpuInputs.data(),
                                                       cpuOutputPosition.data(), cpuOutputColor.data(),
                                                       cpuOutputColor.size(), cpuOutputTexCoord.data(),
                                                       cpuOutputTexCoord.size()),
          "CPU fallback executes NV2A microcode");
    Check(cpuOutputPosition[0] == 2.0f && cpuOutputPosition[1] == 3.0f &&
              cpuOutputPosition[2] == 4.0f && cpuOutputPosition[3] == 1.0f,
          "CPU fallback transforms position");
    Check(cpuOutputTexCoord.front() == 0.0f && cpuOutputTexCoord.back() == 0.0f,
          "CPU fallback returns all four texture-coordinate outputs");

    DWORD translatedDeclaration[8] = {};
    const int declarationTokens =
        XTL::EmuVshTranslateXboxDeclaration(kXboxDeclaration, translatedDeclaration, 8);
    Check(declarationTokens == 3, "declaration token count");
    Check(translatedDeclaration[1] == 0x40020000u, "PC declaration token remains stable");

    std::FILE* capture = nullptr;
#if defined(_WIN32)
    const errno_t captureError = ::tmpfile_s(&capture);
    Check(captureError == 0, "diagnostic capture file result");
#else
    capture = std::tmpfile();
#endif
    Check(capture != nullptr, "diagnostic capture file");
    if(capture != nullptr)
    {
        const XTL::VshDiagnostics::TranslationCapture translationCapture = {
            kXboxProgram,
            translated,
            kXboxDeclaration,
            translatedDeclaration,
        };
        XTL::VshDiagnostics::DumpRejectedTranslation(capture, translationCapture);
        const int seekResult = std::fseek(capture, 0, SEEK_SET);
        Check(seekResult == 0, "diagnostic capture seek");
        if(seekResult == 0)
        {
            char output[256] = {};
            const std::size_t bytesRead = std::fread(output, 1, sizeof(output) - 1, capture);
            Check(std::ferror(capture) == 0, "diagnostic capture read");
            output[bytesRead] = '\0';
            Check(std::strstr(output, "VSH| rejected hash=") != nullptr, "rejection capture header");
        }
        std::fclose(capture);
    }

    delete[] translated;
    if(g_failures == 0)
    {
        std::puts("PASS host vertex-shader recompiler");
    }
    else
    {
        std::printf("INFO hash=0x%08X\n", hash);
    }
    return g_failures;
}

int main()
{
    try
    {
        return RunTests();
    }
    catch(const std::exception& exception)
    {
        std::fprintf(stderr, "FAIL unexpected exception: %s\n", exception.what());
        return 1;
    }
    catch(...)
    {
        std::fputs("FAIL unexpected non-standard exception\n", stderr);
        return 1;
    }
}
