// Generated by tools/trace/gen_trace.py; do not edit.
// generator=1 registry_sha256=543c433c9f5ed6a8c7efc60cd33e1eee6b7d2f617d476bd72c5476815b1bed8d
// Contract: numeric IDs are explicit; tables are sorted by ID; UTF-8/LF output.
#pragma once

#include <cstdint>

#ifndef CXBX_TRACE_HAVE_NV2A
#define CXBX_TRACE_HAVE_NV2A 1
#endif

namespace cxbx::trace
{

inline constexpr std::uint16_t kTraceGrammarVersion = 2;

enum class Channel : std::uint8_t
{
    Kernel = 0,
    Nv2a = 1,
    SingleStep = 2,
    Exception = 3,
    D3dStat = 4,
    D3d = 5,
    Hle = 6,
    FileIo = 7,
    UsbPhysical = 8,
    Reboot = 9,
    Crc = 10,
    Mmio = 11,
    Nv2aMethodStats = 12,
    Count = 13,
};

enum class Event : std::uint16_t
{
    KernelBoundary = 1,
    D3dBoundary = 2,
    FileSystemBoundary = 3,
    MmioAccess = 4,
    Exception = 5,
    BinaryDropped = 6,
    ThreadAttach = 7,
    Continuation0 = 8,
    Continuation1 = 9,
    Continuation2 = 10,
    D3dCall = 11,
    D3dReturn = 12,
    D3dWait = 13,
    Nv2aRead = 14,
    Nv2aWrite = 15,
    Nv2aPush = 16,
    Nv2aMethod = 17,
    Nv2aRamht = 18,
    SingleStepInstruction = 19,
};

enum class D3dApi : std::uint32_t
{
    Clear = 1,
    IsFencePending = 2,
    BlockOnFence = 3,
    BlockUntilIdle = 4,
};

enum class D3dWaitReason : std::uint32_t
{
    SingleStep = 1,
    Fence = 2,
    Idle = 3,
};

struct ChannelDefinition
{
    Channel channel;
    const char* key;
    const char* prefix;
    const char* environmentAlias;
    const char* defaultTier;
    bool available;
};

inline constexpr ChannelDefinition kChannelDefinitions[] = {
    { Channel::Kernel, "ktrace", "KTRACE", nullptr, "text", true },
    { Channel::Nv2a, "nv2a", "NV2A", nullptr, "bin", CXBX_TRACE_HAVE_NV2A != 0 },
    { Channel::SingleStep, "ss", "SS", "CXBX_SS_TRACE", "bin", true },
    { Channel::Exception, "exc", "EXC", "CXBX_EXC_TRACE", "text", true },
    { Channel::D3dStat, "d3dstat", "D3DSTAT", "CXBX_D3D_CALL_STATS", "text", true },
    { Channel::D3d, "d3d", "D3D", nullptr, "text", true },
    { Channel::Hle, "hle", "HLE", "CXBX_HLE_TRACE", "text", true },
    { Channel::FileIo, "fileio", "FILEIO", "CXBX_FILEIO_TRACE", "text", true },
    { Channel::UsbPhysical, "usb", "USBPHYS", "CXBX_USB_PHYS_TRACE", "text", true },
    { Channel::Reboot, "reboot", "REBOOT", "CXBX_REBOOT_TRACE", "text", true },
    { Channel::Crc, "crc", "CRC", "CXBX_CRC_TRACE", "text", true },
    { Channel::Mmio, "mmio", "MMIO", "CXBX_MMIO_TRACE", "bin", true },
    { Channel::Nv2aMethodStats, "nv2a_method_stats", "NV2ASTAT",
      "CXBX_NV2A_METHOD_STATS", "text", true },
};

struct EventDefinition
{
    Event event;
    Channel channel;
    const char* key;
    const char* argument;
};

inline constexpr EventDefinition kEventDefinitions[] = {
    { Event::KernelBoundary, Channel::Kernel, "kernel_boundary", "ordinal" },
    { Event::D3dBoundary, Channel::D3d, "d3d_boundary", "api_id" },
    { Event::FileSystemBoundary, Channel::FileIo, "filesystem_boundary", "transition" },
    { Event::MmioAccess, Channel::Mmio, "mmio_access", "address" },
    { Event::Exception, Channel::Exception, "exception", "code" },
    { Event::BinaryDropped, Channel::Kernel, "binary_dropped", "count" },
    { Event::ThreadAttach, Channel::Kernel, "thread_attach", "thread_id" },
    { Event::Continuation0, Channel::Kernel, "continuation_0", "word" },
    { Event::Continuation1, Channel::Kernel, "continuation_1", "word" },
    { Event::Continuation2, Channel::Kernel, "continuation_2", "word" },
    { Event::D3dCall, Channel::D3d, "d3d_call", "api" },
    { Event::D3dReturn, Channel::D3d, "d3d_return", "api" },
    { Event::D3dWait, Channel::D3d, "d3d_wait", "reason" },
    { Event::Nv2aRead, Channel::Nv2a, "nv2a_read", "offset" },
    { Event::Nv2aWrite, Channel::Nv2a, "nv2a_write", "offset" },
    { Event::Nv2aPush, Channel::Nv2a, "nv2a_push", "word" },
    { Event::Nv2aMethod, Channel::Nv2a, "nv2a_method", "class" },
    { Event::Nv2aRamht, Channel::Nv2a, "nv2a_ramht", "handle" },
    { Event::SingleStepInstruction, Channel::SingleStep, "single_step_instruction", "eip" },
};

constexpr Channel EventChannel(Event event) noexcept
{
    switch(event)
    {
        case Event::KernelBoundary: return Channel::Kernel;
        case Event::D3dBoundary: return Channel::D3d;
        case Event::FileSystemBoundary: return Channel::FileIo;
        case Event::MmioAccess: return Channel::Mmio;
        case Event::Exception: return Channel::Exception;
        case Event::BinaryDropped: return Channel::Kernel;
        case Event::ThreadAttach: return Channel::Kernel;
        case Event::Continuation0: return Channel::Kernel;
        case Event::Continuation1: return Channel::Kernel;
        case Event::Continuation2: return Channel::Kernel;
        case Event::D3dCall: return Channel::D3d;
        case Event::D3dReturn: return Channel::D3d;
        case Event::D3dWait: return Channel::D3d;
        case Event::Nv2aRead: return Channel::Nv2a;
        case Event::Nv2aWrite: return Channel::Nv2a;
        case Event::Nv2aPush: return Channel::Nv2a;
        case Event::Nv2aMethod: return Channel::Nv2a;
        case Event::Nv2aRamht: return Channel::Nv2a;
        case Event::SingleStepInstruction: return Channel::SingleStep;
    }
    return Channel::Count;
}

constexpr std::uint32_t ChannelBit(Channel channel) noexcept
{
    return std::uint32_t{ 1 } << static_cast<std::uint8_t>(channel);
}

static_assert(static_cast<std::uint8_t>(Channel::Count) <= 32,
              "The runtime gate mask supports at most 32 channels");

} // namespace cxbx::trace
