# Generated by tools/trace/gen_trace.py; do not edit.
# generator=1 registry_sha256=4af2a55157268deb060dd071d959e7158efa9521ba6eee249495d314bd7e2667
"""Version-aware parser tables for CXBX structured traces."""

from __future__ import annotations

import re
from typing import Any

GRAMMAR_VERSION = 2
REGISTRY_SHA256 = "4af2a55157268deb060dd071d959e7158efa9521ba6eee249495d314bd7e2667"
CHANNELS: dict[str, dict[str, Any]] = {
    "audio": {
        "availability": None,
        "environment_alias": "CXBX_AUDIO_TRACE",
        "id": 14,
        "prefix": "AUDIO",
        "tier": "bin",
    },
    "crc": {
        "availability": None,
        "environment_alias": "CXBX_CRC_TRACE",
        "id": 10,
        "prefix": "CRC",
        "tier": "text",
    },
    "d3d": {
        "availability": None,
        "environment_alias": None,
        "id": 5,
        "prefix": "D3D",
        "tier": "text",
    },
    "d3dstat": {
        "availability": None,
        "environment_alias": "CXBX_D3D_CALL_STATS",
        "id": 4,
        "prefix": "D3DSTAT",
        "tier": "text",
    },
    "exc": {
        "availability": None,
        "environment_alias": "CXBX_EXC_TRACE",
        "id": 3,
        "prefix": "EXC",
        "tier": "text",
    },
    "fileio": {
        "availability": None,
        "environment_alias": "CXBX_FILEIO_TRACE",
        "id": 7,
        "prefix": "FILEIO",
        "tier": "text",
    },
    "hle": {
        "availability": None,
        "environment_alias": "CXBX_HLE_TRACE",
        "id": 6,
        "prefix": "HLE",
        "tier": "text",
    },
    "ktrace": {
        "availability": None,
        "environment_alias": None,
        "id": 0,
        "prefix": "KTRACE",
        "tier": "text",
    },
    "media": {
        "availability": None,
        "environment_alias": "CXBX_MEDIA_TRACE",
        "id": 13,
        "prefix": "MEDIA",
        "tier": "bin",
    },
    "mmio": {
        "availability": None,
        "environment_alias": "CXBX_MMIO_TRACE",
        "id": 11,
        "prefix": "MMIO",
        "tier": "bin",
    },
    "nv2a": {
        "availability": "CXBX_TRACE_HAVE_NV2A",
        "environment_alias": None,
        "id": 1,
        "prefix": "NV2A",
        "tier": "bin",
    },
    "nv2a_method_stats": {
        "availability": None,
        "environment_alias": "CXBX_NV2A_METHOD_STATS",
        "id": 12,
        "prefix": "NV2ASTAT",
        "tier": "text",
    },
    "reboot": {
        "availability": None,
        "environment_alias": "CXBX_REBOOT_TRACE",
        "id": 9,
        "prefix": "REBOOT",
        "tier": "text",
    },
    "ss": {
        "availability": None,
        "environment_alias": "CXBX_SS_TRACE",
        "id": 2,
        "prefix": "SS",
        "tier": "bin",
    },
    "sync": {
        "availability": None,
        "environment_alias": "CXBX_SYNC_TRACE",
        "id": 15,
        "prefix": "SYNC",
        "tier": "bin",
    },
    "usb": {
        "availability": None,
        "environment_alias": "CXBX_USB_PHYS_TRACE",
        "id": 8,
        "prefix": "USBPHYS",
        "tier": "text",
    },
}
EVENTS: dict[int, dict[str, Any]] = {
    1: {
        "argument": "ordinal",
        "argument_type": "u32",
        "arguments": ["ordinal"],
        "channel": "ktrace",
        "continuations": [],
        "enum": "KernelBoundary",
        "formats": ["hex"],
        "key": "kernel_boundary",
        "verb": None,
    },
    2: {
        "argument": "api_id",
        "argument_type": "u32",
        "arguments": ["api_id"],
        "channel": "d3d",
        "continuations": [],
        "enum": "D3dBoundary",
        "formats": ["hex"],
        "key": "d3d_boundary",
        "verb": None,
    },
    3: {
        "argument": "transition",
        "argument_type": "u32",
        "arguments": ["transition"],
        "channel": "fileio",
        "continuations": [],
        "enum": "FileSystemBoundary",
        "formats": ["hex"],
        "key": "filesystem_boundary",
        "verb": None,
    },
    4: {
        "argument": "address",
        "argument_type": "u32",
        "arguments": ["address"],
        "channel": "mmio",
        "continuations": [],
        "enum": "MmioAccess",
        "formats": ["hex"],
        "key": "mmio_access",
        "verb": None,
    },
    5: {
        "argument": "code",
        "argument_type": "u32",
        "arguments": ["code"],
        "channel": "exc",
        "continuations": [],
        "enum": "Exception",
        "formats": ["hex"],
        "key": "exception",
        "verb": None,
    },
    6: {
        "argument": "count",
        "argument_type": "u32",
        "arguments": ["count"],
        "channel": "ktrace",
        "continuations": [],
        "enum": "BinaryDropped",
        "formats": ["hex"],
        "key": "binary_dropped",
        "verb": None,
    },
    7: {
        "argument": "thread_id",
        "argument_type": "u32",
        "arguments": ["thread_id"],
        "channel": "ktrace",
        "continuations": [],
        "enum": "ThreadAttach",
        "formats": ["hex"],
        "key": "thread_attach",
        "verb": None,
    },
    8: {
        "argument": "word",
        "argument_type": "u32",
        "arguments": ["word"],
        "channel": "ktrace",
        "continuations": [],
        "enum": "Continuation0",
        "formats": ["hex"],
        "key": "continuation_0",
        "verb": None,
    },
    9: {
        "argument": "word",
        "argument_type": "u32",
        "arguments": ["word"],
        "channel": "ktrace",
        "continuations": [],
        "enum": "Continuation1",
        "formats": ["hex"],
        "key": "continuation_1",
        "verb": None,
    },
    10: {
        "argument": "word",
        "argument_type": "u32",
        "arguments": ["word"],
        "channel": "ktrace",
        "continuations": [],
        "enum": "Continuation2",
        "formats": ["hex"],
        "key": "continuation_2",
        "verb": None,
    },
    11: {
        "argument": "api",
        "argument_type": "u32",
        "arguments": ["api", "seq", "flags", "marker"],
        "channel": "d3d",
        "continuations": ["Continuation0", "Continuation1", "Continuation2"],
        "enum": "D3dCall",
        "formats": ["d3d_api", "dec", "hex", "hex"],
        "key": "d3d_call",
        "verb": "call",
    },
    12: {
        "argument": "api",
        "argument_type": "u32",
        "arguments": ["api", "seq", "hr"],
        "channel": "d3d",
        "continuations": ["Continuation0", "Continuation1"],
        "enum": "D3dReturn",
        "formats": ["d3d_api", "dec", "hex"],
        "key": "d3d_return",
        "verb": "ret",
    },
    13: {
        "argument": "reason",
        "argument_type": "u32",
        "arguments": ["reason", "seq", "handle", "pending"],
        "channel": "d3d",
        "continuations": ["Continuation0", "Continuation1", "Continuation2"],
        "enum": "D3dWait",
        "formats": ["d3d_wait_reason", "dec", "hex", "bool"],
        "key": "d3d_wait",
        "verb": "wait",
    },
    14: {
        "argument": "offset",
        "argument_type": "u32",
        "arguments": ["offset", "value"],
        "channel": "nv2a",
        "continuations": ["Continuation0"],
        "enum": "Nv2aRead",
        "formats": ["hex", "hex"],
        "key": "nv2a_read",
        "verb": "rd",
    },
    15: {
        "argument": "offset",
        "argument_type": "u32",
        "arguments": ["offset", "value"],
        "channel": "nv2a",
        "continuations": ["Continuation0"],
        "enum": "Nv2aWrite",
        "formats": ["hex", "hex"],
        "key": "nv2a_write",
        "verb": "wr",
    },
    16: {
        "argument": "word",
        "argument_type": "u32",
        "arguments": ["word"],
        "channel": "nv2a",
        "continuations": [],
        "enum": "Nv2aPush",
        "formats": ["hex"],
        "key": "nv2a_push",
        "verb": "pb",
    },
    17: {
        "argument": "class",
        "argument_type": "u32",
        "arguments": ["class", "method", "data"],
        "channel": "nv2a",
        "continuations": ["Continuation0", "Continuation1"],
        "enum": "Nv2aMethod",
        "formats": ["hex", "hex", "hex"],
        "key": "nv2a_method",
        "verb": "mthd",
    },
    18: {
        "argument": "handle",
        "argument_type": "u32",
        "arguments": ["handle", "instance", "class"],
        "channel": "nv2a",
        "continuations": ["Continuation0", "Continuation1"],
        "enum": "Nv2aRamht",
        "formats": ["hex", "hex", "hex"],
        "key": "nv2a_ramht",
        "verb": "ramht",
    },
    19: {
        "argument": "eip",
        "argument_type": "u32",
        "arguments": ["eip", "esp"],
        "channel": "ss",
        "continuations": ["Continuation0"],
        "enum": "SingleStepInstruction",
        "formats": ["hex", "hex"],
        "key": "single_step_instruction",
        "verb": "step",
    },
    20: {
        "argument": "frame",
        "argument_type": "u32",
        "arguments": ["frame"],
        "channel": "media",
        "continuations": [],
        "enum": "MediaOverlayUpdate",
        "formats": ["dec"],
        "key": "media_overlay_update",
        "verb": "overlay_update",
    },
    21: {
        "argument": "frame",
        "argument_type": "u32",
        "arguments": ["frame"],
        "channel": "media",
        "continuations": [],
        "enum": "MediaPresent",
        "formats": ["dec"],
        "key": "media_present",
        "verb": "present",
    },
    22: {
        "argument": "bytes",
        "argument_type": "u32",
        "arguments": ["bytes"],
        "channel": "audio",
        "continuations": [],
        "enum": "AudioPacketQueued",
        "formats": ["dec"],
        "key": "audio_packet_queued",
        "verb": "packet_queued",
    },
    23: {
        "argument": "bytes",
        "argument_type": "u32",
        "arguments": ["bytes"],
        "channel": "audio",
        "continuations": [],
        "enum": "AudioPacketCompleted",
        "formats": ["dec"],
        "key": "audio_packet_completed",
        "verb": "packet_completed",
    },
    24: {
        "argument": "played_bytes",
        "argument_type": "u32",
        "arguments": ["played_bytes"],
        "channel": "audio",
        "continuations": [],
        "enum": "AudioStarved",
        "formats": ["dec"],
        "key": "audio_starved",
        "verb": "starved",
    },
    25: {
        "argument": "elapsed_ms",
        "argument_type": "u32",
        "arguments": ["elapsed_ms"],
        "channel": "sync",
        "continuations": [],
        "enum": "SyncWaitSatisfied",
        "formats": ["dec"],
        "key": "sync_wait_satisfied",
        "verb": "wait_satisfied",
    },
    26: {
        "argument": "elapsed_ms",
        "argument_type": "u32",
        "arguments": ["elapsed_ms"],
        "channel": "sync",
        "continuations": [],
        "enum": "SyncWaitTimeout",
        "formats": ["dec"],
        "key": "sync_wait_timeout",
        "verb": "wait_timeout",
    },
}
VALUE_SETS: dict[str, dict[str, Any]] = {
    "d3d_api": {
        "enum": "D3dApi",
        "values": {
            1: "Clear",
            2: "IsFencePending",
            3: "BlockOnFence",
            4: "BlockUntilIdle",
        },
    },
    "d3d_wait_reason": {
        "enum": "D3dWaitReason",
        "values": {
            1: "single_step",
            2: "fence",
            3: "idle",
        },
    },
}
PREFIX_TO_CHANNEL = {str(info["prefix"]): key for key, info in sorted(CHANNELS.items())}

_START_RE = re.compile(r"^TRACE\| v=(\d+) start qpc_hz=(\d+)$")
_CHANNEL_RE = re.compile(
    r"^TRACE\| v=(\d+) channel=(\S+) state=(enabled|disabled|unavailable) tier=(text|bin)$"
)
_V2_RE = re.compile(
    r"^(?P<prefix>[A-Z0-9]+)\| (?:(?P<verb>[a-z][a-z0-9_-]*) )?"
    r"tick=(?P<tick>\d+) tid=(?P<tid>0x[0-9A-Fa-f]+) lseq=(?P<lseq>\d+)"
    r"(?: (?P<payload>.*))?$"
)
_FLIGHT_RE = re.compile(
    r"^FLIGHT\| tick=(?P<tick>\d+) tid_ix=(?P<tid_ix>\d+) lseq=(?P<lseq>\d+) "
    r"event=(?P<event>\d+) arg=(?P<arg>0x[0-9A-Fa-f]{8})$"
)


def parse_line(line: str) -> dict[str, Any] | None:
    """Parse a control, canonical event, flight, or legacy channel line."""
    text = line.rstrip("\r\n")
    match = _START_RE.match(text)
    if match:
        return {"kind": "start", "version": int(match[1]), "qpc_hz": int(match[2])}
    match = _CHANNEL_RE.match(text)
    if match:
        return {
            "kind": "channel",
            "version": int(match[1]),
            "channel": match[2],
            "state": match[3],
            "tier": match[4],
        }
    match = _FLIGHT_RE.match(text)
    if match:
        event_id = int(match["event"])
        event = EVENTS.get(event_id)
        return {
            "kind": "flight",
            "version": GRAMMAR_VERSION,
            "tick": int(match["tick"]),
            "thread_index": int(match["tid_ix"]),
            "lseq": int(match["lseq"]),
            "event_id": event_id,
            "event": event["key"] if event else None,
            "argument": int(match["arg"], 16),
        }
    match = _V2_RE.match(text)
    if match and match["prefix"] in PREFIX_TO_CHANNEL:
        return {
            "kind": "event",
            "version": GRAMMAR_VERSION,
            "channel": PREFIX_TO_CHANNEL[match["prefix"]],
            "prefix": match["prefix"],
            "verb": match["verb"],
            "tick": int(match["tick"]),
            "thread_id": int(match["tid"], 16),
            "lseq": int(match["lseq"]),
            "payload": match["payload"] or "",
        }
    for prefix, channel in sorted(PREFIX_TO_CHANNEL.items()):
        marker = prefix + "|"
        if text.startswith(marker):
            return {
                "kind": "legacy",
                "version": 1,
                "channel": channel,
                "prefix": prefix,
                "payload": text[len(marker) :].lstrip(),
            }
    return None


def extract_prefixed_payload(line: str, prefix: str) -> str | None:
    """Return content following the last PREFIX| marker in a decorated line."""
    marker = prefix + "| "
    position = line.rfind(marker)
    return None if position < 0 else line[position + len(marker) :].rstrip("\r\n")


def self_test() -> None:
    start = parse_line(f"TRACE| v={GRAMMAR_VERSION} start qpc_hz=10000000")
    assert start == {"kind": "start", "version": GRAMMAR_VERSION, "qpc_hz": 10000000}
    for key, info in sorted(CHANNELS.items()):
        parsed = parse_line(f"{info['prefix']}| call tick=1 tid=0x00000002 lseq=3 sample=1")
        assert parsed is not None and parsed["channel"] == key and parsed["version"] == 2
    for event_id, event in sorted(EVENTS.items()):
        parsed = parse_line(f"FLIGHT| tick=1 tid_ix=2 lseq=3 event={event_id} arg=0x00000004")
        assert parsed is not None and parsed["event"] == event["key"]
    d3d = parse_line(
        "D3D| call tick=1 tid=0x00000002 lseq=3 api=Clear seq=3 flags=0x00000001 marker=0xD3D0BEEF"
    )
    assert d3d is not None and d3d["verb"] == "call" and d3d["channel"] == "d3d"
    assert extract_prefixed_payload("Emu (0x1): XT| CHK smoke PASS", "XT") == "CHK smoke PASS"
